/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nachoverdon.mss.view;

import javax.swing.border.TitledBorder;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author bazoo
 */
public class CrewPanel extends javax.swing.JPanel {
    private CrewMemberPanel[] members;
    
    /**
     * Creates new form CrewPanel
     */
    public CrewPanel() {
        initComponents();
        initFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelStocks = new javax.swing.JLabel();
        comboBoxName = new javax.swing.JComboBox<>();
        stocksLeft = new javax.swing.JSpinner();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelPlayersName = new javax.swing.JLabel();
        labelPlayerCharacter = new javax.swing.JLabel();
        labalPlayerStocksTaken = new javax.swing.JLabel();
        crewMemberPanel1 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel2 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel3 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel4 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel5 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel6 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel7 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel8 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel9 = new com.nachoverdon.mss.view.CrewMemberPanel();
        crewMemberPanel10 = new com.nachoverdon.mss.view.CrewMemberPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Crew", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        labelName.setText("Name");

        labelStocks.setText("Stocks");

        comboBoxName.setEditable(true);
        comboBoxName.setMaximumSize(new java.awt.Dimension(128, 26));

        jScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));

        labelPlayersName.setText("Name");

        labelPlayerCharacter.setText("Character");

        labalPlayerStocksTaken.setText("Stocks Left/Taken");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPlayersName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPlayerCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labalPlayerStocksTaken))
                    .addComponent(crewMemberPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crewMemberPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayersName)
                    .addComponent(labelPlayerCharacter)
                    .addComponent(labalPlayerStocksTaken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crewMemberPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxName, 0, 220, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stocksLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(labelStocks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stocksLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initFields() {
        try {
            members = new CrewMemberPanel[]{
                crewMemberPanel1,
                crewMemberPanel2,
                crewMemberPanel3,
                crewMemberPanel4,
                crewMemberPanel5,
                crewMemberPanel6,
                crewMemberPanel7,
                crewMemberPanel8,
                crewMemberPanel9,
                crewMemberPanel10
            };
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }
    
    public void setBorderTitle(String title) {
        TitledBorder border = (TitledBorder)getBorder();
        border.setTitle(title);
    }
    
    public JSONObject getInfo() {
        JSONObject json = new JSONObject();
        
        String name = (String) comboBoxName.getSelectedItem();
        
        if (name == null || name.equals("")) return null;
        
        json.put("name", name);
        json.put("stocksLeft", stocksLeft.getValue());
        
        JSONObject membersJson = new JSONObject();
        for (int i = 0; i < members.length; i++) {
            JSONObject member = members[i].getInfo();
            
            if (member == null) continue;
            
            membersJson.put("player" + (i + 1), member);
        }
        json.put("members", membersJson);
        
        return json;
    }
    
    public void setInfo(JSONObject json) {
       comboBoxName.setSelectedItem(json.getString("name"));
       stocksLeft.setValue(json.getInt("stocksLeft"));
       
       JSONObject membersJson = json.getJSONObject("members");
       
       for (int i = 0; i < members.length; i++) {
           try {
            JSONObject member = membersJson.getJSONObject("player" + (i + 1));
            members[i].setInfo(member);   

           } catch (JSONException e) {
               // e.printStackTrace();
               break;
           }
       }
    }
    
    // Get the stocks from enabled crew members and sums them.
    public void calculateStocksLeft() {
        int stocks = 0;
        
        for (CrewMemberPanel member: members) {
            if (member.isEnabled()) {
                stocks += member.getStocksLeft();
            }
        }
        
        stocksLeft.setValue(stocks);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxName;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel1;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel10;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel2;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel3;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel4;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel5;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel6;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel7;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel8;
    private com.nachoverdon.mss.view.CrewMemberPanel crewMemberPanel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labalPlayerStocksTaken;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPlayerCharacter;
    private javax.swing.JLabel labelPlayersName;
    private javax.swing.JLabel labelStocks;
    private javax.swing.JSpinner stocksLeft;
    // End of variables declaration//GEN-END:variables
}