/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nachoverdon.mss.view;

import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author bazoo
 */
public class CrewBattlePanel extends javax.swing.JPanel {

    /**
     * Creates new form CrewBattlePanel
     */
    public CrewBattlePanel() {
        initComponents();
        crewPanel1.setBorderTitle("Crew 1");
        crewPanel2.setBorderTitle("Crew 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crewPanel1 = new com.nachoverdon.mss.view.CrewPanel();
        crewPanel2 = new com.nachoverdon.mss.view.CrewPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(crewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crewPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(crewPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JSONObject getInfo() {
        JSONObject json = new JSONObject(),
            crew1 = crewPanel1.getInfo(),
            crew2 = crewPanel2.getInfo();
        
        if (crew1 == null && crew2 == null) return null;
        
        json.put("crew1", crew1);
        json.put("crew2", crew2);
        
        return json;
    }
    
    public void setInfo(JSONObject json) {
        try {
            JSONObject crew1 = json.getJSONObject("crew1"),
                crew2 = json.getJSONObject("crew2");

            if (crew1 != null) crewPanel1.setInfo(crew1);
            if (crew2 != null) crewPanel2.setInfo(crew2);
        } catch (JSONException e) {
            // No crews
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nachoverdon.mss.view.CrewPanel crewPanel1;
    private com.nachoverdon.mss.view.CrewPanel crewPanel2;
    // End of variables declaration//GEN-END:variables
}
