/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nachoverdon.mss.view;

import com.nachoverdon.mss.utils.AutoCompletion;
import com.nachoverdon.mss.utils.ComboBoxUtils;
import com.nachoverdon.mss.utils.FileUtils;
import org.json.JSONObject;

/**
 *
 * @author Nacho Verdón Blázquez
 */
public class GeneralInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralInfoPanel
     */
    public GeneralInfoPanel() {
        initComponents();
        initFields();
        enableAutocompletion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRound = new javax.swing.JLabel();
        labelBestOf = new javax.swing.JLabel();
        comboBoxRound = new javax.swing.JComboBox<>();
        spinnerBestOf = new javax.swing.JSpinner();
        labelTournamentName = new javax.swing.JLabel();
        labelBracket = new javax.swing.JLabel();
        comboBoxTournamentName = new javax.swing.JComboBox<>();
        comboBoxBracket = new javax.swing.JComboBox<>();
        labelWebsite = new javax.swing.JLabel();
        labelTwitch = new javax.swing.JLabel();
        comboBoxWebsite = new javax.swing.JComboBox<>();
        comboBoxTwitch = new javax.swing.JComboBox<>();
        labelCaster1 = new javax.swing.JLabel();
        labelCaster2 = new javax.swing.JLabel();
        comboBoxCaster1 = new javax.swing.JComboBox<>();
        comboBoxCaster2 = new javax.swing.JComboBox<>();
        labelPlayerCam1 = new javax.swing.JLabel();
        labelPlayerCam2 = new javax.swing.JLabel();
        comboBoxPlayerCam1 = new javax.swing.JComboBox<>();
        comboBoxPlayerCam2 = new javax.swing.JComboBox<>();
        labelPlayerCam3 = new javax.swing.JLabel();
        labelPlayerCam4 = new javax.swing.JLabel();
        comboBoxPlayerCam3 = new javax.swing.JComboBox<>();
        comboBoxPlayerCam4 = new javax.swing.JComboBox<>();
        buttonSwapCasters = new javax.swing.JButton();
        buttonSwapPlayerCam1And2 = new javax.swing.JButton();
        buttonSwapPlayerCam3And4 = new javax.swing.JButton();
        buttonSwapPlayerCam1And3 = new javax.swing.JButton();
        buttonSwapPlayerCam2And4 = new javax.swing.JButton();
        buttonGetDataFromPlayerPanel = new javax.swing.JButton();

        labelRound.setText("Round");

        labelBestOf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelBestOf.setText("Best Of");

        comboBoxRound.setEditable(true);
        comboBoxRound.setMaximumSize(new java.awt.Dimension(128, 26));

        labelTournamentName.setText("Tournament name");

        labelBracket.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelBracket.setText("Bracket");

        comboBoxTournamentName.setEditable(true);
        comboBoxTournamentName.setMaximumSize(new java.awt.Dimension(128, 26));

        comboBoxBracket.setEditable(true);
        comboBoxBracket.setMaximumSize(new java.awt.Dimension(128, 26));

        labelWebsite.setText("Website");

        labelTwitch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTwitch.setText("Twitch");

        comboBoxWebsite.setEditable(true);
        comboBoxWebsite.setMaximumSize(new java.awt.Dimension(128, 26));

        comboBoxTwitch.setEditable(true);
        comboBoxTwitch.setMaximumSize(new java.awt.Dimension(128, 26));

        labelCaster1.setText("Caster 1");

        labelCaster2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCaster2.setText("Caster 2");

        comboBoxCaster1.setEditable(true);
        comboBoxCaster1.setMaximumSize(new java.awt.Dimension(128, 26));

        comboBoxCaster2.setEditable(true);
        comboBoxCaster2.setMaximumSize(new java.awt.Dimension(128, 26));

        labelPlayerCam1.setText("Player Cam 1");

        labelPlayerCam2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPlayerCam2.setText("Player Cam 2");

        comboBoxPlayerCam1.setEditable(true);
        comboBoxPlayerCam1.setMaximumSize(new java.awt.Dimension(128, 26));

        comboBoxPlayerCam2.setEditable(true);
        comboBoxPlayerCam2.setMaximumSize(new java.awt.Dimension(128, 26));

        labelPlayerCam3.setText("Player Cam 3");

        labelPlayerCam4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPlayerCam4.setText("Player Cam 4");

        comboBoxPlayerCam3.setEditable(true);
        comboBoxPlayerCam3.setMaximumSize(new java.awt.Dimension(128, 26));

        comboBoxPlayerCam4.setEditable(true);
        comboBoxPlayerCam4.setMaximumSize(new java.awt.Dimension(128, 26));

        buttonSwapCasters.setText("↔");
        buttonSwapCasters.setPreferredSize(new java.awt.Dimension(43, 20));
        buttonSwapCasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapCastersActionPerformed(evt);
            }
        });

        buttonSwapPlayerCam1And2.setText("↔");
        buttonSwapPlayerCam1And2.setPreferredSize(new java.awt.Dimension(43, 20));
        buttonSwapPlayerCam1And2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapPlayerCam1And2ActionPerformed(evt);
            }
        });

        buttonSwapPlayerCam3And4.setText("↔");
        buttonSwapPlayerCam3And4.setPreferredSize(new java.awt.Dimension(43, 20));
        buttonSwapPlayerCam3And4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapPlayerCam3And4ActionPerformed(evt);
            }
        });

        buttonSwapPlayerCam1And3.setText("↕");
        buttonSwapPlayerCam1And3.setPreferredSize(new java.awt.Dimension(39, 20));
        buttonSwapPlayerCam1And3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapPlayerCam1And3ActionPerformed(evt);
            }
        });

        buttonSwapPlayerCam2And4.setText("↕");
        buttonSwapPlayerCam2And4.setPreferredSize(new java.awt.Dimension(39, 20));
        buttonSwapPlayerCam2And4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapPlayerCam2And4ActionPerformed(evt);
            }
        });

        buttonGetDataFromPlayerPanel.setText("📑");
        buttonGetDataFromPlayerPanel.setToolTipText("Get player names from the Players panel");
        buttonGetDataFromPlayerPanel.setPreferredSize(new java.awt.Dimension(43, 20));
        buttonGetDataFromPlayerPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetDataFromPlayerPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxPlayerCam3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPlayerCam3)
                                .addGap(153, 153, 153)
                                .addComponent(buttonSwapPlayerCam1And3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSwapPlayerCam3And4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonGetDataFromPlayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxRound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTournamentName, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCaster1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxCaster1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPlayerCam1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(comboBoxPlayerCam1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSwapCasters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSwapPlayerCam1And2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxTournamentName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelWebsite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(comboBoxWebsite, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerBestOf, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboBoxPlayerCam4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxCaster2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxPlayerCam2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonSwapPlayerCam2And4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(153, 153, 153)
                            .addComponent(labelPlayerCam4))
                        .addComponent(comboBoxBracket, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBestOf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxTwitch, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTwitch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBracket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelCaster2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlayerCam2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRound)
                    .addComponent(labelBestOf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerBestOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTournamentName)
                    .addComponent(labelBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTournamentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxBracket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWebsite)
                    .addComponent(labelTwitch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaster1)
                    .addComponent(labelCaster2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCaster1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSwapCasters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCaster2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayerCam1)
                    .addComponent(labelPlayerCam2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPlayerCam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSwapPlayerCam1And2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPlayerCam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSwapPlayerCam1And3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGetDataFromPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSwapPlayerCam2And4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlayerCam4)
                    .addComponent(labelPlayerCam3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxPlayerCam4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonSwapPlayerCam3And4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxPlayerCam3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSwapCastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapCastersActionPerformed
        ComboBoxUtils.swapSelectedItems(comboBoxCaster1, comboBoxCaster2);
    }//GEN-LAST:event_buttonSwapCastersActionPerformed

    private void buttonSwapPlayerCam1And2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapPlayerCam1And2ActionPerformed
        ComboBoxUtils.swapSelectedItems(comboBoxPlayerCam1, comboBoxPlayerCam2);
    }//GEN-LAST:event_buttonSwapPlayerCam1And2ActionPerformed

    private void buttonSwapPlayerCam1And3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapPlayerCam1And3ActionPerformed
        ComboBoxUtils.swapSelectedItems(comboBoxPlayerCam1, comboBoxPlayerCam3);
    }//GEN-LAST:event_buttonSwapPlayerCam1And3ActionPerformed

    private void buttonSwapPlayerCam2And4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapPlayerCam2And4ActionPerformed
        ComboBoxUtils.swapSelectedItems(comboBoxPlayerCam2, comboBoxPlayerCam4);
    }//GEN-LAST:event_buttonSwapPlayerCam2And4ActionPerformed

    private void buttonSwapPlayerCam3And4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapPlayerCam3And4ActionPerformed
        ComboBoxUtils.swapSelectedItems(comboBoxPlayerCam3, comboBoxPlayerCam4);
    }//GEN-LAST:event_buttonSwapPlayerCam3And4ActionPerformed

    private void buttonGetDataFromPlayerPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetDataFromPlayerPanelActionPerformed
        // TODO: There should be a better way to retrieve the PlayersInfoPanel.
        PlayersInfoPanel playersPanel = (PlayersInfoPanel)getParent() // JTabbedPane
                .getComponent(0); // PlayerInfoPanel
        JSONObject json = playersPanel.getInfo();
        comboBoxPlayerCam1.setSelectedItem(json.getJSONObject("player1").getString("name"));
        comboBoxPlayerCam2.setSelectedItem(json.getJSONObject("player2").getString("name"));
        comboBoxPlayerCam3.setSelectedItem(json.getJSONObject("player3").getString("name"));
        comboBoxPlayerCam4.setSelectedItem(json.getJSONObject("player4").getString("name"));
    }//GEN-LAST:event_buttonGetDataFromPlayerPanelActionPerformed

    private void initFields() {
        try {
            initRounds();
            initCasters();
            initPlayerCam();
        } catch (NullPointerException e) {
            e.printStackTrace();
        }
    }
    
    private void enableAutocompletion() {
        AutoCompletion.enable(comboBoxRound);
        AutoCompletion.enable(comboBoxTournamentName);
        AutoCompletion.enable(comboBoxBracket);
        AutoCompletion.enable(comboBoxCaster1);
        AutoCompletion.enable(comboBoxCaster2);
        AutoCompletion.enable(comboBoxPlayerCam1);
        AutoCompletion.enable(comboBoxPlayerCam2);
        AutoCompletion.enable(comboBoxPlayerCam3);
        AutoCompletion.enable(comboBoxPlayerCam4);
        AutoCompletion.enable(comboBoxWebsite);
        AutoCompletion.enable(comboBoxTwitch);
    }
    
    private void initRounds() {
        comboBoxRound.addItem("");
        
        for (String round: FileUtils.getRounds()) {
            comboBoxRound.addItem(round);
        }
    }
    
    private void initPlayerCam() {       
        ComboBoxUtils.initPlayers(comboBoxPlayerCam1);
        ComboBoxUtils.initPlayers(comboBoxPlayerCam2);
        ComboBoxUtils.initPlayers(comboBoxPlayerCam3);
        ComboBoxUtils.initPlayers(comboBoxPlayerCam4);
    }
    
    private void initCasters() {
        comboBoxCaster1.addItem("");
        comboBoxCaster2.addItem("");
        
        for (String caster: FileUtils.getCasters()) {
            comboBoxCaster1.addItem(caster);
            comboBoxCaster2.addItem(caster);
        }
    }
    
    public JSONObject getInfo() {
        JSONObject json = new JSONObject();
        
        json.put("round", comboBoxRound.getSelectedItem());
        json.put("bestof", spinnerBestOf.getValue());
        json.put("tournament", comboBoxTournamentName.getSelectedItem());
        json.put("bracket", comboBoxBracket.getSelectedItem());
        json.put("caster1", comboBoxCaster1.getSelectedItem());
        json.put("caster2", comboBoxCaster2.getSelectedItem());
        json.put("player1", comboBoxPlayerCam1.getSelectedItem());
        json.put("player2", comboBoxPlayerCam2.getSelectedItem());
        json.put("player3", comboBoxPlayerCam3.getSelectedItem());
        json.put("player4", comboBoxPlayerCam4.getSelectedItem());
        json.put("website", comboBoxWebsite.getSelectedItem());
        json.put("twitch", comboBoxTwitch.getSelectedItem());
        return json;
    }
    
    public void setInfo(JSONObject json) {
        comboBoxRound.setSelectedItem(json.getString("round"));
        spinnerBestOf.setValue(json.getInt("bestof"));
        comboBoxTournamentName.setSelectedItem(json.getString("tournament"));
        comboBoxBracket.setSelectedItem(json.getString("bracket"));
        comboBoxCaster1.setSelectedItem(json.getString("caster1"));
        comboBoxCaster2.setSelectedItem(json.getString("caster2"));
        comboBoxPlayerCam1.setSelectedItem(json.getString("player1"));
        comboBoxPlayerCam2.setSelectedItem(json.getString("player2"));
        comboBoxPlayerCam3.setSelectedItem(json.getString("player3"));
        comboBoxPlayerCam4.setSelectedItem(json.getString("player4"));
        comboBoxWebsite.setSelectedItem(json.getString("website"));
        comboBoxTwitch.setSelectedItem(json.getString("twitch"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGetDataFromPlayerPanel;
    private javax.swing.JButton buttonSwapCasters;
    private javax.swing.JButton buttonSwapPlayerCam1And2;
    private javax.swing.JButton buttonSwapPlayerCam1And3;
    private javax.swing.JButton buttonSwapPlayerCam2And4;
    private javax.swing.JButton buttonSwapPlayerCam3And4;
    private javax.swing.JComboBox<String> comboBoxBracket;
    private javax.swing.JComboBox<String> comboBoxCaster1;
    private javax.swing.JComboBox<String> comboBoxCaster2;
    private javax.swing.JComboBox<String> comboBoxPlayerCam1;
    private javax.swing.JComboBox<String> comboBoxPlayerCam2;
    private javax.swing.JComboBox<String> comboBoxPlayerCam3;
    private javax.swing.JComboBox<String> comboBoxPlayerCam4;
    private javax.swing.JComboBox<String> comboBoxRound;
    private javax.swing.JComboBox<String> comboBoxTournamentName;
    private javax.swing.JComboBox<String> comboBoxTwitch;
    private javax.swing.JComboBox<String> comboBoxWebsite;
    private javax.swing.JLabel labelBestOf;
    private javax.swing.JLabel labelBracket;
    private javax.swing.JLabel labelCaster1;
    private javax.swing.JLabel labelCaster2;
    private javax.swing.JLabel labelPlayerCam1;
    private javax.swing.JLabel labelPlayerCam2;
    private javax.swing.JLabel labelPlayerCam3;
    private javax.swing.JLabel labelPlayerCam4;
    private javax.swing.JLabel labelRound;
    private javax.swing.JLabel labelTournamentName;
    private javax.swing.JLabel labelTwitch;
    private javax.swing.JLabel labelWebsite;
    private javax.swing.JSpinner spinnerBestOf;
    // End of variables declaration//GEN-END:variables
}
